version: '3.7'
services:
  app:
    # get last hash from https://docs.lido.fi/guides/tooling#validator-ejector
    image: 2020jack/validator-ejector:v1.9.1
    container_name: validator-ejector
    restart: unless-stopped
    network_mode: host
    environment:
      - EXECUTION_NODE=${EXECUTION_NODE}
      - CONSENSUS_NODE=${CONSENSUS_NODE}
      - JWT_SECRET_PATH=${JWT_SECRET_PATH}
      - LOCATOR_ADDRESS=${LOCATOR_ADDRESS}
      - STAKING_MODULE_ID=${STAKING_MODULE_ID}
      - OPERATOR_ID=${OPERATOR_ID}
      - MESSAGES_LOCATION=${MESSAGES_LOCATION}
      - MESSAGES_PASSWORD=${MESSAGES_PASSWORD}
      - MESSAGES_PASSWORD_FILE=${MESSAGES_PASSWORD_FILE}
      - VALIDATOR_EXIT_WEBHOOK=${VALIDATOR_EXIT_WEBHOOK}
      - ORACLE_ADDRESSES_ALLOWLIST=${ORACLE_ADDRESSES_ALLOWLIST}
      - EASY_TRACK_MOTION_CREATOR_ADDRESSES_ALLOWLIST=${EASY_TRACK_MOTION_CREATOR_ADDRESSES_ALLOWLIST}
      - SUBMIT_TX_HASH_ALLOWLIST=${SUBMIT_TX_HASH_ALLOWLIST}
      - EASY_TRACK_ADDRESS=${EASY_TRACK_ADDRESS}
      - BLOCKS_PRELOAD=${BLOCKS_PRELOAD}
      - HTTP_PORT=${HTTP_PORT}
      - RUN_METRICS=${RUN_METRICS}
      - RUN_HEALTH_CHECK=${RUN_HEALTH_CHECK}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - LOGGER_FORMAT=${LOGGER_FORMAT}
      - LOGGER_SECRETS=${LOGGER_SECRETS}
      - DRY_RUN=${DRY_RUN}
      - TRUST_MODE=${TRUST_MODE}
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
    volumes:
      - ./messages:/app/messages
      - ${JWT_SECRET_PATH}:${JWT_SECRET_PATH}:ro

